version: '3.1'
services: 
  backend:
    build: ./BACKEND
    ports: 
      - 80:8800
    env_file: 
      - ./env/backend.env
    depends_on:
      - postgres
  postgres:
    image: postgres:15.2-alpine
    env_file: 
      - ./env/postgres.env 
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init/:/docker-entrypoint-initdb.d/
